### PR TITLE
App json update

### PR DESCRIPTION
**Pull request by ghost**
I added the missing environment parameter to app/wedeploy.json and it will work well. Tested on my local system and prod as well.
Solution came from [Rocket Chat install documentation](https://rocket.chat/docs/installation/docker-containers/index.html#6-create-the-docker-composeyml-file--local-directories)

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
I'm still getting:

```
[rockett] Deploy in progress [app] as rocket.chat:0.58
app[191627ef]
app[191627ef] /app/bundle/programs/server/node_modules/fibers/future.js:313
app[191627ef] throw(ex);
app[191627ef] ^
app[191627ef] MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 10.8.177.2:27017]
app[191627ef] at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
app[191627ef] at new MongoConnection (packages/mongo/mongo_driver.js:210:27)
app[191627ef] at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
app[191627ef] at Object.&lt;anonymous> (packages/mongo/remote_collection_driver.js:38:10)
app[191627ef] at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
app[191627ef] at new Mongo.Collection (packages/mongo/collection.js:99:40)
app[191627ef] at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
app[191627ef] at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
app[191627ef] at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
app[191627ef] at fileEvaluate (packages/modules-runtime.js:333:9)
app[191627ef] - - - - -
app[191627ef] at [object Object].&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:329:35)
app[191627ef] at emitOne (events.js:77:13)
app[191627ef] at [object Object].emit (events.js:169:7)
app[191627ef] at [object Object].&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
app[191627ef] at [object Object].g (events.js:260:16)
app[191627ef] at emitTwo (events.js:87:13)
app[191627ef] at [object Object].emit (events.js:172:7)
app[191627ef] at Socket.&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
app[191627ef] at Socket.g (events.js:260:16)
app[191627ef] at emitOne (events.js:77:13)
app[88b619c5]
app[88b619c5] /app/bundle/programs/server/node_modules/fibers/future.js:313
app[88b619c5] throw(ex);
app[88b619c5] ^
app[88b619c5] MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 10.8.177.2:27017]
app[88b619c5] at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
app[88b619c5] at new MongoConnection (packages/mongo/mongo_driver.js:210:27)
app[88b619c5] at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
app[88b619c5] at Object.&lt;anonymous> (packages/mongo/remote_collection_driver.js:38:10)
app[88b619c5] at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
app[88b619c5] at new Mongo.Collection (packages/mongo/collection.js:99:40)
app[88b619c5] at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
app[88b619c5] at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
app[88b619c5] at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
app[88b619c5] at fileEvaluate (packages/modules-runtime.js:333:9)
app[88b619c5] - - - - -
app[88b619c5] at [object Object].&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:329:35)
app[88b619c5] at emitOne (events.js:77:13)
app[88b619c5] at [object Object].emit (events.js:169:7)
app[88b619c5] at [object Object].&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
app[88b619c5] at [object Object].g (events.js:260:16)
app[88b619c5] at emitTwo (events.js:87:13)
app[88b619c5] at [object Object].emit (events.js:172:7)
app[88b619c5] at Socket.&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
app[88b619c5] at Socket.g (events.js:260:16)
app[88b619c5] at emitOne (events.js:77:13)
app[33b154bb]
app[33b154bb] /app/bundle/programs/server/node_modules/fibers/future.js:313
app[33b154bb] throw(ex);
app[33b154bb] ^
app[33b154bb] MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 10.8.177.2:27017]
app[33b154bb] at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
app[33b154bb] at new MongoConnection (packages/mongo/mongo_driver.js:210:27)
app[33b154bb] at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
app[33b154bb] at Object.&lt;anonymous> (packages/mongo/remote_collection_driver.js:38:10)
app[33b154bb] at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
app[33b154bb] at new Mongo.Collection (packages/mongo/collection.js:99:40)
app[33b154bb] at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
app[33b154bb] at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
app[33b154bb] at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
app[33b154bb] at fileEvaluate (packages/modules-runtime.js:333:9)
app[33b154bb] - - - - -
app[33b154bb] at [object Object].&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:329:35)
app[33b154bb] at emitOne (events.js:77:13)
app[33b154bb] at [object Object].emit (events.js:169:7)
app[33b154bb] at [object Object].&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
app[33b154bb] at [object Object].g (events.js:260:16)
app[33b154bb] at emitTwo (events.js:87:13)
app[33b154bb] at [object Object].emit (events.js:172:7)
app[33b154bb] at Socket.&lt;anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
app[33b154bb] at Socket.g (events.js:260:16)
app[33b154bb] at emitOne (events.js:77:13)
```

**Comment by ghost** [comment]
This is an known issue on prod. The db still not started yel, but the app try to use the db. 
Suggested solution: Apply healthcheck on db.
Progress: I am testing it now on prod.

**Comment by ghost** [comment]
I tested it on with the new volume driver on XYZ and it seems be okay. I created account for me and it is still working as well.

Validation URL: https://app-p1.wedeploy.sh/

app[build] ce2597c38559: Pushed
app[build] ua3ycr7: digest: sha256:6204f4894352422a85d3258373d0eee7909cb6dfb48e2a9c4e030fe92ebb2361 size: 2420
[p1] Deploy in progress [app] as rocket.chat:0.58
app[c8cf1b6c] Will load cache for users
app[c8cf1b6c] 0 records load from users
app[c8cf1b6c] Will load cache for rocketchat_room
app[c8cf1b6c] 0 records load from rocketchat_room
app[c8cf1b6c] Will load cache for rocketchat_subscription
app[c8cf1b6c] 0 records load from rocketchat_subscription
app[c8cf1b6c] Will load cache for rocketchat_settings
app[c8cf1b6c] 0 records load from rocketchat_settings
app[c8cf1b6c] Updating process.env.MAIL_URL
app[c8cf1b6c] Will load cache for rocketchat_permissions
app[c8cf1b6c] 0 records load from rocketchat_permissions
app[c8cf1b6c] Will load cache for rocketchat_roles
app[c8cf1b6c] 0 records load from rocketchat_roles
app[c8cf1b6c] LocalStore: store created at
app[c8cf1b6c] LocalStore: store created at
app[c8cf1b6c] Setting default file store to GridFS
app[c8cf1b6c] Updating process.env.MAIL_URL
app[c8cf1b6c] Using GridFS for custom sounds storage
app[c8cf1b6c] Using GridFS for custom emoji storage
app[c8cf1b6c] ufs: temp directory created at "/tmp/ufs"
app[c8cf1b6c] ➔ System ➔ startup
app[c8cf1b6c] ➔ +----------------------------------------------+
app[c8cf1b6c] ➔ | SERVER RUNNING |
app[c8cf1b6c] ➔ +----------------------------------------------+
app[c8cf1b6c] ➔ | |
app[c8cf1b6c] ➔ | Rocket.Chat Version: 0.58.4 |
app[c8cf1b6c] ➔ | NodeJS Version: 4.8.4 - x64 |
app[c8cf1b6c] ➔ | Platform: linux |
app[c8cf1b6c] ➔ | Process Port: 3000 |
app[c8cf1b6c] ➔ | Site URL: http://localhost:3000 |
app[c8cf1b6c] ➔ | ReplicaSet OpLog: Disabled |
app[c8cf1b6c] ➔ | Commit Hash: 60fa18c32e |
app[c8cf1b6c] ➔ | Commit Branch: heads/0.58.4 |
app[c8cf1b6c] ➔ | |
app[c8cf1b6c] ➔ +----------------------------------------------+

**Comment by zenorocha** [comment]
Awesome, merging!

**Pull request merged**
